name: pw test

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs: 
  e2eTests:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps: 
      # Делаем чекаут
      - uses: actions/checkout@v4
      
      # Устанавливаем nodejs
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Устанавливаем пакеты node
      - name: установить пакеты
        run: npm i
      
      # Устанавливаем PW
      - name: Install PW
        run: npx playwright install --with-deps
      
      # Запускаем тесты
      - name: Запустить тесты
        run: npm run test
        
      # Сохраняем результаты allure
      - uses: actions/upload-artifact@v4
        if: always()
        continue-on-error: true
        with:
          name: allure-results
          path: allure-results
          retention-days: 20
      
      # Забираем результаты предыдущего запуска
      - uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      
      # Формируем из allure-result отчет allure-report
      - uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with: 
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      # Деплоим отчет
      - name: deploy report
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
          
      
