name: pw tests with allure

on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  e2eTests:
    # timeout-minutes: 30
    runs-on: ubuntu-latest
    
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Setup Node.js
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      
      # Install dependencies
      - name: Install dependencies
        run: npm install
      
      # Install Playwright
      - name: Install Playwright
        run: npx playwright install --with-deps
      
      # Run tests
      - name: Run Playwright tests
        run: npx playwright test
      
      # Upload test results
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        continue-on-error: true
        with:
          name: test-results
          path: test-results
          retention-days: 20
      
      # Upload Allure results
      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        if: always()
        continue-on-error: true
        with:
          name: allure-results
          path: allure-results
          retention-days: 20
      
      # Checkout gh-pages branch
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
      
      # Generate Allure report
      - name: Generate Allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        continue-on-error: true
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20
      
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
