name: pw test

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs: 
  e2eTests:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Важно для работы с историей

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: установить пакеты
        run: npm i
      
      - name: Install PW
        run: npx playwright install --with-deps
      
      - name: Запустить тесты
        run: npm run test
        
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: allure-results
          retention-days: 20
      
      - name: Generate Allure Report
        if: always()
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results
          allure_report: allure-report
          keep_reports: 5

      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          force_orphan: true  # Полная очистка ветки перед деплоем
